# Docker Compose 版本声明
version: '3'

# 服务定义
services:
  # JWT 服务配置
  jwt-server:
    build: .
    container_name: jwt-server
    restart: always
    volumes:
      # 挂载私钥文件
      - ./private_key.pem:/app/private_key.pem

  # Nginx 反向代理服务配置
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      # 端口映射：主机端口:容器端口
      - "80:80"
    volumes:
      # 挂载 Nginx 配置文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jwt-server